-- MySQL Script generated by MySQL Workbench
-- Tue Aug 13 12:37:58 2019
-- Model: SVDB    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `name` VARCHAR(20) NOT NULL,
  `admin_id` INT(11) NOT NULL,
  `admin_password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`admin_id`),
  UNIQUE INDEX `admin_admin_id_uindex` (`admin_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`item_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_details` (
  `Item_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Item_name` VARCHAR(30) NOT NULL,
  `Item_rate` FLOAT NOT NULL,
  `Item_measure` VARCHAR(20) NOT NULL,
  `Item_image` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`Item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_details` (
  `Name` VARCHAR(50) NOT NULL,
  `Address` VARCHAR(100) NULL DEFAULT 'NULL',
  `Contact_no` VARCHAR(15) NOT NULL,
  `email_id` VARCHAR(50) NOT NULL,
  `User_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`User_id`),
  UNIQUE INDEX `user_details_User_id_uindex` (`User_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pickup_person_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pickup_person_details` (
  `Name` VARCHAR(50) NOT NULL,
  `Contact_no` INT(15) NOT NULL,
  `Aadhar_no` INT(12) NOT NULL,
  `Pickup_person_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Salary` FLOAT NOT NULL,
  `Rating` INT(5) NULL DEFAULT '0',
  `Pickup_person_status` VARCHAR(25) NULL DEFAULT 'working',
  PRIMARY KEY (`Pickup_person_id`),
  UNIQUE INDEX `pickup_person_details_Pickup_person_id_uindex` (`Pickup_person_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`booking_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`booking_details` (
  `User_id` INT(11) NOT NULL,
  `Booking_date_time` DATETIME NOT NULL,
  `Scheduled_pickup_date_time` DATETIME NOT NULL,
  `Pickup_date_time` DATETIME NULL DEFAULT NULL,
  `Booking_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Pickup_person_id` INT(11) NOT NULL,
  `Pickup_status` VARCHAR(20) NOT NULL,
  `Pickup_person_rating` INT(5) NULL DEFAULT NULL,
  PRIMARY KEY (`Booking_id`),
  UNIQUE INDEX `booking_details_Booking_id_uindex` (`Booking_id` ASC) VISIBLE,
  INDEX `booking_details_fk0` (`User_id` ASC) VISIBLE,
  INDEX `booking_details_fk1` (`Pickup_person_id` ASC) VISIBLE,
  CONSTRAINT `booking_details___fk0`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`user_details` (`User_id`),
  CONSTRAINT `booking_details___fk1`
    FOREIGN KEY (`Pickup_person_id`)
    REFERENCES `mydb`.`pickup_person_details` (`Pickup_person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`booked_item_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`booked_item_list` (
  `Item_id` INT(11) NOT NULL,
  `Booking_id` INT(11) NOT NULL,
  `Item_qty` FLOAT NOT NULL,
  `Item_amount` FLOAT NOT NULL,
  `Pickup_timestamp` TIMESTAMP NOT NULL,
  INDEX `booked_item_list_fk0` (`Item_id` ASC) VISIBLE,
  INDEX `booked_item_list_fk1` (`Booking_id` ASC) VISIBLE,
  CONSTRAINT `booked_item_list___fk0`
    FOREIGN KEY (`Item_id`)
    REFERENCES `mydb`.`item_details` (`Item_id`),
  CONSTRAINT `booked_item_list___fk1`
    FOREIGN KEY (`Booking_id`)
    REFERENCES `mydb`.`booking_details` (`Booking_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`company_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company_details` (
  `Company_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Company_name` VARCHAR(50) NOT NULL,
  `Address` VARCHAR(50) NOT NULL,
  `Contact_no` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Company_id`),
  UNIQUE INDEX `company_details_Company_id_uindex` (`Company_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`company_sale_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company_sale_details` (
  `Company_id` INT(11) NOT NULL,
  `Sales_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Sales_amount` FLOAT NOT NULL,
  `Date` DATETIME NOT NULL,
  `Sale_status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Sales_id`),
  UNIQUE INDEX `company_sale_details_Sales_id_uindex` (`Sales_id` ASC) VISIBLE,
  INDEX `company_sale_details_fk0` (`Company_id` ASC) VISIBLE,
  CONSTRAINT `company_sale_details___fk0`
    FOREIGN KEY (`Company_id`)
    REFERENCES `mydb`.`company_details` (`Company_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`contact_us`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact_us` (
  `Author` VARCHAR(30) NOT NULL,
  `Email` VARCHAR(30) NOT NULL,
  `Contact_no` INT(15) NOT NULL,
  `Subject` VARCHAR(50) NOT NULL,
  `Message` VARCHAR(255) NOT NULL,
  `Contact_id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Contact_id`),
  UNIQUE INDEX `contact_id_UNIQUE` (`Contact_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`order_cancel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_cancel` (
  `Booking_id` INT(11) NOT NULL,
  `Cancellation_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Feedback` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`Cancellation_id`),
  UNIQUE INDEX `order_cancel_Cancellation_id_uindex` (`Cancellation_id` ASC) VISIBLE,
  INDEX `order_cancel___fk0` (`Booking_id` ASC) VISIBLE,
  CONSTRAINT `order_cancel___fk0`
    FOREIGN KEY (`Booking_id`)
    REFERENCES `mydb`.`booking_details` (`Booking_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`payment_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment_details` (
  `Payment_id` INT(11) NOT NULL,
  `Payment_amount` FLOAT NOT NULL,
  `Booking_id` INT(11) NOT NULL,
  `Payment_mode` VARCHAR(20) NULL DEFAULT 'online',
  `Payment_status` VARCHAR(20) NULL DEFAULT 'pending',
  PRIMARY KEY (`Payment_id`),
  INDEX `payment_details_fk0` (`Booking_id` ASC) VISIBLE,
  CONSTRAINT `payment_details___fk0`
    FOREIGN KEY (`Booking_id`)
    REFERENCES `mydb`.`booking_details` (`Booking_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pickup_person_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pickup_person_record` (
  `Pickup_person_id` INT(11) NOT NULL,
  `Date` TIMESTAMP NOT NULL,
  `10:00AM-12:00PM` TINYINT(4) NULL DEFAULT '1',
  `12:00PM-02:00PM` TINYINT(4) NULL DEFAULT '1',
  `02:00PM-04:00PM` TINYINT(4) NULL DEFAULT '1',
  `04:00PM-06:00PM` TINYINT(4) NULL DEFAULT '1',
  INDEX `pickup_person_record_fk0` (`Pickup_person_id` ASC) VISIBLE,
  CONSTRAINT `pickup_person_record___fk0`
    FOREIGN KEY (`Pickup_person_id`)
    REFERENCES `mydb`.`pickup_person_details` (`Pickup_person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
